# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      env: 
        mongotest_db_uri: ${{ secrets.mongotest_db_uri }} 
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@
      with:
        node-version: ${{ matrix.node-version }}
        mongotest_db_uri: ${{ secrets.mongotest_db_uri }}
    - run : ${{ env.mongotest_db_uri }}    
    - run: cd frontend && npm ci
    - run: cd frontend && npm run build --if-present
    - run: cd frontend && CI=true npm test
    - run: cd server && npm ci
    - run: cd server && npm run build --if-present
    - run: cd server && CI=true npm test
      env:
        CI: true
